#!/usr/bin/env python3
"""Bulk-download the chosen Sketchfab models on your own computer and drop them into inbound/sketchfab/.

Standalone: save this one file anywhere and run it (Python 3.8+, no extra packages). Inside a clone it fills
inbound/sketchfab, elsewhere ./sketchfab-models:

    python3 sketchfab-download.py                 # all 39 sources
    python3 sketchfab-download.py g3 m16 spear    # just these ids
    python3 sketchfab-download.py --list          # show what it would fetch

Token: set SKETCHFAB_TOKEN in your environment, or the script asks for it (input is hidden). Find it on
sketchfab.com > Settings > Password & API. The token is only sent to api.sketchfab.com and is never written to disk.

Afterwards put the models in the repository so the next agent session can import them. In a clone:

    git add inbound/sketchfab && git commit -m "Sketchfab sources" && git push

Otherwise copy the sketchfab-models folder to inbound/sketchfab in your clone (rename it) and do the same.

Already-downloaded models are skipped, so you can stop and re-run at any time.
"""
import argparse
import getpass
import json
import os
import shutil
import sys
import time
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent if (HERE.parent / "inbound").is_dir() else None  # a clone of the repository, if run from one of its folders
DEFAULT_OUT = (REPO / "inbound" / "sketchfab") if REPO else Path.cwd() / "sketchfab-models"
# The model list is embedded so this file works on its own (generated by tools/assets/build-outbound-downloader.mjs).
SOURCES_JSON = r'''{
  "note": "Chosen Sketchfab sources for every procedurally built Workbench attachment and every roadmap weapon/asset. Fetch with: SKETCHFAB_TOKEN=... node tools/assets/sketchfab-fetch.mjs [id ...]. 'take' names the part to extract when the model is a donor (a whole rifle or a set). Credits and licences: see the GitHub documentation (ADR 0012). length: real longest dimension in metres (the import scales to it); unit 'du': D_U's shared model unit, scaled like the AK-74M (0.943 m / 9.088 units) so his parts fit his rifles. dir: assets/models/<dir>/.",
  "style": "D_U (DU1701) first: the AK-74M and AK-15K already in the project are his, so his parts match scale, palette and polygon density.",
  "sources": [
    {
      "id": "muzzle-set",
      "for": [
        "attachments: ak74 brake",
        "attachments: comp"
      ],
      "uid": "07f62ec5ca604446848d1a0238b11f1d",
      "name": "low-poly Muzzle Device Set",
      "author": "DU1701",
      "faces": 2642,
      "unit": "du",
      "dir": "weapons"
    },
    {
      "id": "suppressor-ak",
      "for": [
        "attachments: can (suppressor)"
      ],
      "uid": "67d899ced2614887850c9af820786a89",
      "name": "Low-poly AK hexagon suppressor",
      "author": "notcplkerry",
      "faces": 3548,
      "length": 0.2,
      "dir": "weapons"
    },
    {
      "id": "collimator-set",
      "for": [
        "attachments: micro (micro dot)",
        "attachments: holo (holographic)"
      ],
      "uid": "288373d26dd84db2898920222ac3e430",
      "name": "low-poly Collimator Set",
      "author": "DU1701",
      "faces": 10330,
      "unit": "du",
      "dir": "weapons"
    },
    {
      "id": "eotech",
      "for": [
        "attachments: holo (alternative)"
      ],
      "uid": "5c8f29d9895e48e183a085fefabf0e14",
      "name": "EOTech HWS XPS2 Sight (Low-Poly)",
      "author": "GoldbergR",
      "faces": 3146,
      "length": 0.16,
      "dir": "weapons"
    },
    {
      "id": "scope-zf4",
      "for": [
        "attachments: scope (4x)"
      ],
      "uid": "bd60e97c17fc42bbb9e1622caffc2a03",
      "name": "ZF-4 Scope (Low-Poly)",
      "author": "GoldbergR",
      "faces": 2719,
      "length": 0.28,
      "dir": "weapons"
    },
    {
      "id": "iron-sight-set",
      "for": [
        "attachments: flip (back-up sight)"
      ],
      "uid": "dd89d27a54474b2aa3bf1cadc699c556",
      "name": "low-poly Iron Sight Set",
      "author": "DU1701",
      "faces": 10104,
      "unit": "du",
      "dir": "weapons"
    },
    {
      "id": "rail-ak",
      "for": [
        "attachments: rail (top rail mount)"
      ],
      "uid": "615c65f9670b42d3bcdd015119a771a4",
      "name": "AK Optics Mount Rail (Low Poly)",
      "author": "armoredwave",
      "faces": 1500,
      "length": 0.15,
      "dir": "weapons"
    },
    {
      "id": "grip-rvg",
      "for": [
        "attachments: vertical (foregrip)"
      ],
      "uid": "86b3580a65c441db9d3401712c5c9b6d",
      "name": "Low-Poly Magpul RVG",
      "author": "notcplkerry",
      "faces": 534,
      "length": 0.1,
      "dir": "weapons"
    },
    {
      "id": "grip-afg",
      "for": [
        "attachments: angled (foregrip)"
      ],
      "uid": "a92a52cbb5854f7c8e33507f579073f7",
      "name": "Low-Poly Magpul AFG",
      "author": "notcplkerry",
      "faces": 1418,
      "length": 0.11,
      "dir": "weapons"
    },
    {
      "id": "peq15",
      "for": [
        "attachments: laser",
        "attachments: combo (light + laser)"
      ],
      "uid": "522f6a04c34946dbb168022187645c1a",
      "name": "low-poly AN/PEQ 15",
      "author": "DU1701",
      "faces": 3552,
      "unit": "du",
      "dir": "weapons"
    },
    {
      "id": "peq2",
      "for": [
        "attachments: laser (alternative)"
      ],
      "uid": "820ee672677a4f8daab617f1723820a2",
      "name": "low-poly AN/PEQ 2",
      "author": "DU1701",
      "faces": 2094,
      "unit": "du",
      "dir": "weapons"
    },
    {
      "id": "light-surefire",
      "for": [
        "attachments: light (weapon light)"
      ],
      "uid": "09bba490e5e44ac6a412cc363eb2b41e",
      "name": "SureFire 660 Weapon Light with Pressure Switch",
      "author": "haoliu95",
      "faces": 4410,
      "length": 0.17,
      "dir": "weapons"
    },
    {
      "id": "ak-grips",
      "for": [
        "attachments: classic (plum pistol grip)",
        "attachments: stop (hand stop, from the set if present)"
      ],
      "uid": "044c2b403fc341738b5af9f3b90fefc9",
      "name": "Low-Poly AK grips",
      "author": "notcplkerry",
      "faces": 1990,
      "dir": "weapons"
    },
    {
      "id": "rpk-762",
      "for": [
        "attachments: 45 (RPK magazine)",
        "weapon: RPK (replaces the AK-74M kitbash, WP-A14)"
      ],
      "take": "magazine and the whole rifle",
      "uid": "628d823c021f4bfa814a66674ac658dc",
      "name": "low-poly RPK 7.62",
      "author": "DU1701",
      "faces": 20699,
      "unit": "du",
      "dir": "weapons",
      "strip": [
        "76239_12",
        "7.62x39_13",
        "ak 40rnd steel mag_16"
      ]
    },
    {
      "id": "ak74-drum",
      "for": [
        "attachments: drum (drum magazine)"
      ],
      "take": "drum magazine",
      "uid": "8ae00f51dc1649b8b5b592d153f3a3f4",
      "name": "Low poly Ak74 + drum mag + gl",
      "author": "aayushsahaywork",
      "faces": 16519,
      "length": 0.943,
      "dir": "weapons"
    },
    {
      "id": "aks74",
      "for": [
        "attachments: stock none / folding stock donor",
        "attachments: 60 (quad-stack: donor for an AK magazine to widen)"
      ],
      "take": "stock, magazine",
      "uid": "0ef0540be4e94ef1bdcfc7ecfea56a31",
      "name": "low-poly AKS-74",
      "author": "DU1701",
      "faces": 19393,
      "unit": "du",
      "dir": "weapons"
    },
    {
      "id": "gp25",
      "for": [
        "convoy: grenadier launcher",
        "attachments: under-barrel launcher (new)"
      ],
      "uid": "8dbdec74bad944a9b7eca73b2a6269fa",
      "name": "low-poly GP-25",
      "author": "DU1701",
      "faces": 3954,
      "unit": "du",
      "dir": "weapons"
    },
    {
      "id": "g3",
      "for": [
        "weapon: G3A3 (WP-A9)"
      ],
      "uid": "86ff01824c394e349cda876a827fa69c",
      "name": "low-poly HK G3",
      "author": "DU1701",
      "faces": 8926,
      "length": 1.025,
      "dir": "weapons",
      "strip": [
        "76251_6",
        "76251 g3mag 30rnd_8"
      ]
    },
    {
      "id": "g3-drum",
      "for": [
        "G3 attachment: .308 drum"
      ],
      "uid": "4acf799d7ec04383ae664937224d3537",
      "name": "Low-Poly .308 Drum Magazine",
      "author": "notcplkerry",
      "faces": 996,
      "length": 0.2,
      "dir": "weapons"
    },
    {
      "id": "g3-bipod",
      "for": [
        "G3 attachment: steel bipod"
      ],
      "uid": "b525a696d09d48a484db53c2002d02fb",
      "name": "HK G3 Steel Bipod (Low-Poly)",
      "author": "GoldbergR",
      "faces": 576,
      "length": 0.3,
      "dir": "weapons"
    },
    {
      "id": "g3-scope",
      "for": [
        "G3 attachment: Hensoldt Z-24 scope"
      ],
      "uid": "c6d7df8cbe954a64a3e5bcbc324255b3",
      "name": "Hensoldt Z-24 Scope (Low-Poly)",
      "author": "GoldbergR",
      "faces": 1728,
      "length": 0.24,
      "dir": "weapons"
    },
    {
      "id": "m16",
      "for": [
        "weapon: M16 (WP-A12)"
      ],
      "uid": "f7eddeb852f84094a7ba26e293223d10",
      "name": "Low-Poly M16",
      "author": "TastyTony",
      "faces": 5989,
      "length": 1.0,
      "dir": "weapons"
    },
    {
      "id": "mk14",
      "for": [
        "weapon: Mk14 EBR (WP-A13)"
      ],
      "uid": "0dc89b4028ef4a1bbc1ed2ec077f3d21",
      "name": "Low-Poly Mk14 EBR",
      "author": "TastyTony",
      "faces": 11746,
      "length": 0.889,
      "dir": "weapons"
    },
    {
      "id": "spear",
      "for": [
        "weapon: SIG Spear (WP-A15, no purchase needed)"
      ],
      "uid": "36ac159795ae465e8a4d44068bbaf434",
      "name": "low-poly SIG MCX Spear",
      "author": "DU1701",
      "faces": 25668,
      "unit": "du",
      "dir": "weapons",
      "strip": [
        "277 ar-10 mag empty 30rnd (lancer)_2",
        "277_0"
      ]
    },
    {
      "id": "stg44",
      "for": [
        "weapon: StG 44 modernised (WP-A16)"
      ],
      "uid": "c343d3531806490e851976d4f0391c14",
      "name": "low-poly Stg44",
      "author": "DU1701",
      "faces": 6146,
      "unit": "du",
      "dir": "weapons",
      "strip": [
        "Cube.001_6",
        "Cylinder.013_5",
        "Cylinder.016_4"
      ]
    },
    {
      "id": "ppsh41",
      "for": [
        "weapon: PPSh-41 modernised (WP-A17)"
      ],
      "uid": "d610bf73066d4bb7a96834858772384a",
      "name": "low-poly PPSH-41",
      "author": "DU1701",
      "faces": 5620,
      "unit": "du",
      "dir": "weapons",
      "strip": [
        "Cylinder.003_4",
        "Cylinder.001_3"
      ]
    },
    {
      "id": "bren",
      "for": [
        "weapon: Bren (WP-A18)"
      ],
      "uid": "035555d607c142528e2eaf4c02af8c5b",
      "name": "Low-Poly Bren Gun",
      "author": "TastyTony",
      "faces": 4048,
      "length": 1.15,
      "dir": "weapons",
      "tint": "#5a5d60"
    },
    {
      "id": "chauchat",
      "for": [
        "weapon: Chauchat (WP-A18)"
      ],
      "uid": "ae9d3c2b5c3542e0829aac8d0cb7d6e5",
      "name": "Low-Poly Chauchat",
      "author": "TastyTony",
      "faces": 9373,
      "length": 1.143,
      "dir": "weapons"
    },
    {
      "id": "checkpoint-barrier",
      "for": [
        "environment kit (WP-E1)",
        "convoy roadblock"
      ],
      "uid": "cd64979fc9774d729ac31e443a9f3935",
      "name": "Checkpoint Stop Road Barrier lowpoly",
      "author": "00amza",
      "faces": 356,
      "length": 3.5,
      "dir": "environment"
    },
    {
      "id": "jersey-barrier-damaged",
      "for": [
        "environment kit (WP-E1)"
      ],
      "uid": "599abb4a62074fefafa788c0bcb71841",
      "name": "Damaged Concrete Barrier low poly",
      "author": "malekabdeltwab",
      "faces": 412,
      "length": 3.0,
      "dir": "environment"
    },
    {
      "id": "sandbag",
      "for": [
        "environment kit (WP-E1)",
        "convoy cover"
      ],
      "uid": "7d52600a15c747749d845d9f906045cf",
      "name": "Sandbag [Low Poly Realist]",
      "author": "Islide",
      "faces": 712,
      "length": 0.7,
      "dir": "environment"
    },
    {
      "id": "pallet",
      "for": [
        "environment kit (WP-E1)"
      ],
      "uid": "2f1abd705d4f4118b4c8d0b275441505",
      "name": "Wooden Pallet Low-poly",
      "author": "MaX3Dd",
      "faces": 1372,
      "length": 1.2,
      "dir": "environment"
    },
    {
      "id": "containers",
      "for": [
        "environment kit (WP-E1)"
      ],
      "uid": "4579520c83694ba18b3573192265276c",
      "name": "Cargo Containers Very Low Poly",
      "author": "Nelesh_surve",
      "faces": 1320,
      "length": 6.06,
      "dir": "environment"
    },
    {
      "id": "church-kit",
      "for": [
        "environment kit (WP-E1): ruin pieces"
      ],
      "uid": "8b13eb65288c4ee58b128f47067f7998",
      "name": "Low-Poly Church - Modular Kit",
      "author": "sj_memo",
      "faces": 48127,
      "dir": "environment"
    },
    {
      "id": "radio-handheld",
      "for": [
        "Recon gear prop: handheld radio (WP-C3)"
      ],
      "uid": "4ef0ec44f77e4d928791e245763e3f45",
      "name": "[Low Poly] Handheld Radio/Phone",
      "author": "that0neprogrammer",
      "faces": 836,
      "length": 0.25,
      "dir": "props"
    },
    {
      "id": "canister",
      "for": [
        "Recon gear prop: canister (WP-C3)"
      ],
      "uid": "7f9027faa52d4a0ba3a3c630a4013b4f",
      "name": "Military Gas Can | Low Poly",
      "author": "alpha_Arts",
      "faces": 638,
      "length": 0.47,
      "dir": "props"
    },
    {
      "id": "matv",
      "for": [
        "convoy: MRAP"
      ],
      "uid": "32a28aaea1f048b0a70d5f215f288b04",
      "name": "M-ATV (low-poly)",
      "author": "ScurvyWoof",
      "faces": 28391,
      "length": 6.27,
      "dir": "vehicles"
    },
    {
      "id": "army-truck",
      "for": [
        "convoy: truck"
      ],
      "uid": "9fd961a22cb84b9383570869b2f0efa9",
      "name": "low poly military truck",
      "author": "KolosStudios",
      "faces": 696,
      "length": 7.0,
      "dir": "vehicles"
    },
    {
      "id": "humvee",
      "for": [
        "convoy: jeeps"
      ],
      "uid": "e862680472b047528f1955683873181c",
      "name": "AM General HMMWV",
      "author": "SoapEmi",
      "faces": 12774,
      "length": 4.57,
      "dir": "vehicles"
    }
  ]
}'''
API = "https://api.sketchfab.com/v3/models/{uid}/download"
UA = "partisan-project-asset-fetch/1.0"


def read_secret(prompt, getwch=None):
    """Read a secret and show one * per character (a plain hidden prompt looks frozen, especially on Windows).
    Paste works (right-click or Ctrl+Shift+V). Enter finishes, Backspace deletes. `getwch` is injectable for tests."""
    if getwch is None:
        try:
            import msvcrt  # Windows
            getwch = msvcrt.getwch
        except ImportError:
            return getpass.getpass(prompt + "(hidden, paste then press Enter): ")
    print(prompt + "(paste it, then press Enter; you will see * as it arrives): ", end="", flush=True)
    chars = []
    while True:
        ch = getwch()
        if ch in ("\r", "\n"):
            print()
            return "".join(chars)
        if ch == "\x03":
            raise KeyboardInterrupt
        if ch in ("\x08", "\x7f"):
            if chars:
                chars.pop()
                print("\b \b", end="", flush=True)
        elif ch in ("\x00", "\xe0"):
            getwch()  # swallow the second half of a function or arrow key
        elif ch >= " ":
            chars.append(ch)
            print("*", end="", flush=True)


def request(url, token=None, retries=3):
    headers = {"User-Agent": UA}
    if token:  # only ever for api.sketchfab.com
        headers["Authorization"] = f"Token {token}"
    for attempt in range(retries):
        try:
            return urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=300)
        except urllib.error.HTTPError as e:
            if e.code in (401, 403):
                raise SystemExit(f"Sketchfab refused the token ({e.code}). Check it on sketchfab.com > Settings > Password & API.")
            if e.code == 429 or e.code >= 500:  # rate limit or a hiccup: back off and retry
                time.sleep(5 * (attempt + 1))
                continue
            raise
        except urllib.error.URLError:
            time.sleep(3 * (attempt + 1))
    raise RuntimeError(f"gave up after {retries} tries: {url.split('?')[0]}")


def download(url, dest):
    tmp = dest.with_suffix(dest.suffix + ".part")
    with request(url) as r, open(tmp, "wb") as f:  # signed URL: no token
        total = int(r.headers.get("Content-Length") or 0)
        done = 0
        while chunk := r.read(1 << 20):
            f.write(chunk)
            done += len(chunk)
            if total:
                print(f"\r      {done / 1e6:6.1f} / {total / 1e6:.1f} MB", end="", flush=True)
    print()
    tmp.replace(dest)


def fetch(source, token, out_root):
    out = out_root / source["id"]
    if (out / "scene.glb").exists() or (out / "scene.gltf").exists():
        return "skip"
    with request(API.format(uid=source["uid"]), token) as r:
        info = json.load(r)
    out.mkdir(parents=True, exist_ok=True)
    if info.get("glb", {}).get("url"):
        download(info["glb"]["url"], out / "scene.glb")
    elif info.get("gltf", {}).get("url"):
        archive = out / "download.zip"
        download(info["gltf"]["url"], archive)
        with zipfile.ZipFile(archive) as z:
            z.extractall(out)
        archive.unlink()
        # some archives nest everything one folder down: lift it up so scene.gltf sits in out/
        if not (out / "scene.gltf").exists():
            found = next(out.rglob("scene.gltf"), None) or next(out.rglob("*.gltf"), None)
            if found:
                for item in found.parent.iterdir():
                    shutil.move(str(item), out / item.name)
                if found.name != "scene.gltf" and (out / found.name).exists():
                    (out / found.name).rename(out / "scene.gltf")
    else:
        shutil.rmtree(out, ignore_errors=True)
        return "no glTF offered (the model may no longer be downloadable)"
    (out / "source.json").write_text(json.dumps(source, indent=1) + "\n")
    return "ok"


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("ids", nargs="*", help="source ids from sketchfab-sources.json (default: all)")
    p.add_argument("--list", action="store_true", help="list the sources and exit")
    p.add_argument("--no-pause", action="store_true", help="do not wait for Enter at the end (Windows)")
    p.add_argument("--out", default=str(DEFAULT_OUT), help="where to put them (default: inbound/sketchfab in a clone, else ./sketchfab-models)")
    a = p.parse_args()
    sources = json.loads(SOURCES_JSON)["sources"]
    if a.ids:
        unknown = set(a.ids) - {s["id"] for s in sources}
        if unknown:
            raise SystemExit(f"unknown ids: {', '.join(sorted(unknown))} (see --list)")
        sources = [s for s in sources if s["id"] in a.ids]
    if a.list:
        for s in sources:
            print(f"{s['id']:24} {s['author']:18} {s['name']}")
        return
    token = os.environ.get("SKETCHFAB_TOKEN") or read_secret("Sketchfab API token ").strip()
    if not token:
        raise SystemExit("No token given.")
    out_root = Path(a.out)
    out_root.mkdir(parents=True, exist_ok=True)
    failed = []
    for i, s in enumerate(sources, 1):
        print(f"[{i}/{len(sources)}] {s['id']}  ({s['name']})")
        try:
            result = fetch(s, token, out_root)
        except SystemExit:
            raise
        except Exception as e:  # keep going; report at the end
            result = f"failed: {e}"
        print(f"      {result}")
        if result not in ("ok", "skip"):
            failed.append((s["id"], result))
        time.sleep(1)  # be gentle with the API
    print(f"\nDone: {len(sources) - len(failed)}/{len(sources)} in {out_root}")
    for sid, why in failed:
        print(f"  {sid}: {why}")
    if not failed:
        print('Next: git add inbound/sketchfab && git commit -m "Sketchfab sources" && git push')
    sys.exit(1 if failed else 0)


def pause_before_closing():
    """A double-clicked script's window vanishes when it ends; on Windows wait so the result can be read."""
    if os.name == "nt" and sys.stdin and sys.stdin.isatty() and "--no-pause" not in sys.argv:
        try:
            input("\nPress Enter to close this window.")
        except (EOFError, KeyboardInterrupt):
            pass


if __name__ == "__main__":
    try:
        main()
    except SystemExit as e:
        if e.code not in (None, 0) and isinstance(e.code, str):
            print(e.code)  # show the message before the window closes
        pause_before_closing()
        raise SystemExit(0 if e.code in (None, 0) else 1)
    except KeyboardInterrupt:
        print("\nCancelled.")
        pause_before_closing()
        raise SystemExit(1)
    pause_before_closing()
