// Generates docs/CODEMAP.md: one line per source file (path, size, purpose from its first comment).
// Agents read this instead of listing and opening files, which is the cheapest context there is.
//   node tools/agent/codemap.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
const ROOTS = [
  'index.html',
  'assets/js',
  'assets/css',
  'shared',
  'workbench',
  'operator',
  'viewer',
  'tools',
  'tests',
  '.github/workflows',
  'docs',
];
const SKIP = /node_modules|vendor|moodboard|docs\/ai|partisan-ai|\.glb$|\.hdr$|\.mp3$|\.jpg$|\.png$|\.svg$|\.json$|\.csv$/;
const EXT = /\.(m?js|py|css|html|md|yml)$/;
const walk = p =>
  !fs.existsSync(p)
    ? []
    : fs.statSync(p).isDirectory()
      ? fs
          .readdirSync(p)
          .sort()
          .flatMap(e => walk(path.join(p, e)))
      : [p];
function purpose(file, text) {
  const lines = text
    .split('\n')
    .slice(0, 14)
    .map(l => l.trim());
  if (file.endsWith('.md')) return (lines.find(l => l.startsWith('# ')) || '').replace(/^#\s*/, '');
  if (file.endsWith('.html')) return (text.match(/<title>([^<]*)<\/title>/) || [])[1] || '';
  if (file.endsWith('.py')) {
    const m = text.match(/^"""([^\n]*)/);
    return m ? m[1] : '';
  }
  const first = lines.find(l => /^(\/\/|\/\*|\*)/.test(l) && !/^\/\/\s*(usage|@ts)/i.test(l));
  return (first || '')
    .replace(/^(\/\/+|\/\*+|\*+)\s?/, '')
    .replace(/\*\/$/, '')
    .trim();
}
const out = [
  '# Code map',
  '',
  'Generated by `node tools/agent/codemap.mjs`. One line per file: path · lines · purpose. Read this before opening files.',
  '',
];
let dir = '';
for (const file of ROOTS.flatMap(walk)
  .map(f => f.split(path.sep).join('/'))
  .filter(f => EXT.test(f) && !SKIP.test(f))) {
  const d = path.dirname(file);
  if (d !== dir) {
    dir = d;
    out.push('', `### ${d}/`, '');
  }
  const text = fs.readFileSync(file, 'utf8');
  out.push(`- \`${path.basename(file)}\` · ${text.split('\n').length} · ${purpose(file, text).slice(0, 140)}`);
}
const body = out.join('\n') + '\n';
if (process.argv.includes('--check')) {
  const cur = fs.existsSync('docs/CODEMAP.md') ? fs.readFileSync('docs/CODEMAP.md', 'utf8') : '';
  if (cur !== body) {
    console.error('docs/CODEMAP.md is stale: run node tools/agent/codemap.mjs');
    process.exit(1);
  }
  console.log('codemap in sync');
} else {
  fs.writeFileSync('docs/CODEMAP.md', body);
  console.log(`codemap: ${body.split('\n').length} lines`);
}
