// Shared 3D stage for PARP modules: renderer, orbit camera, HDR image-based lighting that follows
// the camera, a shadow-catching floor and adaptive resolution. The Operator Customiser and the
// Asset Viewer use it. (The Weapon Workbench still carries its own copy of this logic in
// workbench/viewer.js; folding it in is tracked as WP-TD-01 in docs/master-roadmap.md.)
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';

const hdr=name=>new URL(`../assets/lighting/${name}`,import.meta.url).href;
export const ENVIRONMENTS={
  studio:hdr('studio.hdr'),                 // generated by tools/assets/generate-studio-hdr.py
  outdoor:hdr('quarry_01_1k.hdr'),          // Poly Haven "Quarry 01", CC0
  sunset:hdr('venice_sunset_1k.hdr'),       // Poly Haven "Venice Sunset", CC0
};

export const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;

/**
 * @param {HTMLElement} container  element the canvas is prepended to
 * @param {object} opts
 * @param {string} [opts.environment='sunset']
 * @param {boolean} [opts.backdrop=true]   show the blurred HDR as the background
 * @param {number} [opts.lightOffset=255]  degrees the lighting is turned from the camera
 * @param {number} [opts.heroAzimuth=-0.2] azimuth the lighting was authored from (radians)
 * @param {number} [opts.floorSize=6]
 */
export async function createStage(container, opts = {}) {
  const {environment = 'sunset', backdrop = true, lightOffset = 255, heroAzimuth = -0.2, floorSize = 6} = opts;
  const small = matchMedia('(max-width: 780px), (pointer: coarse)').matches;

  const renderer = new T.WebGLRenderer({antialias: true, alpha: true});
  renderer.setPixelRatio(Math.min(devicePixelRatio, small ? 1.5 : 2));
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = T.PCFSoftShadowMap;
  renderer.toneMapping = T.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.1;
  container.prepend(renderer.domElement);

  const scene = new T.Scene();
  const camera = new T.PerspectiveCamera(35, 1, 0.01, 60);
  const controls = new OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.minDistance = 0.3;
  controls.maxDistance = 8;

  const floor = new T.Mesh(new T.PlaneGeometry(floorSize, floorSize), new T.ShadowMaterial({opacity: 0.3}));
  floor.rotation.x = -Math.PI / 2;
  floor.receiveShadow = true;
  scene.add(floor);

  // The directional key only casts the shadow; it is aimed at the HDR's brightest texel.
  const key = new T.DirectionalLight(0xffffff, 1.6);
  key.castShadow = true;
  key.shadow.mapSize.setScalar(small ? 1024 : 2048);
  Object.assign(key.shadow.camera, {left: -2, right: 2, top: 2.5, bottom: -1, near: 0.5, far: 12});
  key.shadow.normalBias = 0.01;
  key.shadow.radius = 4;
  scene.add(key, key.target);

  const hdrLoader = new RGBELoader().setDataType(T.FloatType);
  const environments = {};
  let envName = environment, lightAngle = lightOffset, hooks = [], cameraMove = null;

  function brightestDirection(texture) {
    const {data, width, height} = texture.image;
    let best = -1, at = 0;
    for (let i = 0; i < width * height; i++) {
      const l = data[i * 4] * 0.2126 + data[i * 4 + 1] * 0.7152 + data[i * 4 + 2] * 0.0722;
      if (l > best) { best = l; at = i; }
    }
    const az = ((at % width + 0.5) / width - 0.5) * Math.PI * 2;
    const el = (0.5 - (Math.floor(at / width) + 0.5) / height) * Math.PI;
    return new T.Vector3(Math.cos(el) * Math.cos(az), Math.max(Math.sin(el), 0.35), Math.cos(el) * Math.sin(az)).normalize();
  }

  async function useEnvironment(name) {
    if (!environments[name]) {
      const texture = await hdrLoader.loadAsync(ENVIRONMENTS[name]);
      texture.mapping = T.EquirectangularReflectionMapping;
      environments[name] = {texture, sun: brightestDirection(texture)};
    }
    envName = name;
    scene.environment = environments[name].texture;
    if (scene.background) scene.background = scene.environment;
    for (const b of document.querySelectorAll('[data-env]')) b.setAttribute('aria-pressed', String(b.dataset.env === name));
  }

  function setBackdrop(on) {
    scene.background = on ? scene.environment : null;
    scene.backgroundBlurriness = 0.5;
    scene.backgroundIntensity = 0.55;
    document.querySelector('#backdrop')?.setAttribute('aria-pressed', String(on));
  }

  function rotateLights(degrees) {
    lightAngle = ((degrees % 360) + 360) % 360;
    const slider = document.querySelector('#light-rotation');
    if (slider) slider.value = String(Math.round(lightAngle));
    const out = document.querySelector('#light-angle');
    if (out) out.textContent = Math.round(lightAngle) + '°';
  }

  // Lighting turns with the camera azimuth plus the user's offset, so it stays put relative to the view.
  const up = new T.Vector3(0, 1, 0);
  function orientLights() {
    const r = controls.getAzimuthalAngle() - heroAzimuth + T.MathUtils.degToRad(lightAngle);
    scene.environmentRotation.y = scene.backgroundRotation.y = r;
    if (environments[envName]) {
      key.position.copy(environments[envName].sun).applyAxisAngle(up, r).multiplyScalar(4).add(key.target.position);
    }
  }

  const resize = () => {
    const w = container.clientWidth, h = container.clientHeight;
    if (!w || !h) return;
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
    renderer.setSize(w, h);
  };
  new ResizeObserver(resize).observe(container);
  resize();

  await useEnvironment(envName);
  rotateLights(lightAngle);
  setBackdrop(backdrop);

  // Alt/shift-drag turns the lights instead of the camera.
  let lightDrag = null;
  container.addEventListener('pointerdown', e => {
    if (!e.altKey && !e.shiftKey) return;
    e.preventDefault();
    lightDrag = {x: e.clientX, angle: lightAngle};
    controls.enabled = false;
  }, {capture: true});
  addEventListener('pointermove', e => { if (lightDrag) rotateLights(lightDrag.angle + (e.clientX - lightDrag.x) * 0.5); });
  addEventListener('pointerup', () => { if (lightDrag) { lightDrag = null; controls.enabled = true; } });
  renderer.domElement.addEventListener('pointerdown', () => { cameraMove = null; });

  // Keyboard camera (WCAG 2.1.1): arrows orbit, + / - zoom, Home resets the azimuth. The stage container must be focusable (tabindex=0).
  container.addEventListener('keydown', e => {
    if (e.target !== container || e.ctrlKey || e.metaKey || e.altKey) return;
    const v = camera.position.clone().sub(controls.target);
    if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') v.applyAxisAngle(up, e.key === 'ArrowLeft' ? 0.1 : -0.1);
    else if (e.key === 'ArrowUp' || e.key === 'ArrowDown') v.applyAxisAngle(new T.Vector3(1, 0, 0).applyQuaternion(camera.quaternion).setY(0).normalize(), e.key === 'ArrowUp' ? 0.1 : -0.1);
    else if (e.key === '+' || e.key === '=') v.multiplyScalar(0.9);
    else if (e.key === '-') v.multiplyScalar(1.1);
    else return;
    e.preventDefault();
    cameraMove = null;
    camera.position.copy(controls.target).add(v);
    controls.update();
  });

  /** Glide the camera to look at `target` from `position` (instant under reduced motion). */
  function moveCamera(target, position, seconds = 0.45) {
    if (reduceMotion) { controls.target.copy(target); camera.position.copy(position); controls.update(); return; }
    cameraMove = {t: 0, seconds, fromTarget: controls.target.clone(), fromPosition: camera.position.clone(), toTarget: target.clone(), toPosition: position.clone()};
  }

  // Adaptive resolution: every 2 s drop the pixel ratio while frames average over 28 ms, raise it with headroom.
  const maxRatio = renderer.getPixelRatio();
  let frames = 0, windowStart = performance.now();
  function adaptResolution() {
    frames++;
    const now = performance.now(), elapsed = (now - windowStart) / 1000;
    if (elapsed < 2) return;
    const avg = elapsed / frames, ratio = renderer.getPixelRatio();
    frames = 0; windowStart = now;
    if (document.hidden) return;
    const next = avg > 0.028 ? Math.max(1, ratio - 0.25) : avg < 0.014 ? Math.min(maxRatio, ratio + 0.25) : ratio;
    if (next !== ratio) { renderer.setPixelRatio(next); resize(); }
  }

  const clock = new T.Clock();
  /** Register a per-frame callback `(dt, elapsedSeconds)`. dt is capped so slow frames never skip animation. */
  const onFrame = fn => hooks.push(fn);
  renderer.setAnimationLoop(() => {
    const dt = Math.min(clock.getDelta(), 1 / 30);
    for (const fn of hooks) fn(dt, clock.elapsedTime);
    if (cameraMove) {
      cameraMove.t = Math.min(1, cameraMove.t + dt / cameraMove.seconds);
      const e = 1 - (1 - cameraMove.t) ** 4;
      controls.target.lerpVectors(cameraMove.fromTarget, cameraMove.toTarget, e);
      camera.position.lerpVectors(cameraMove.fromPosition, cameraMove.toPosition, e);
      if (cameraMove.t >= 1) cameraMove = null;
    }
    key.target.updateMatrixWorld();
    controls.update();
    orientLights();
    renderer.render(scene, camera);
    adaptResolution();
  });

  for (const b of document.querySelectorAll('[data-env]')) b.onclick = () => useEnvironment(b.dataset.env);
  document.querySelector('#light-rotation')?.addEventListener('input', e => rotateLights(Number(e.target.value)));
  const backdropButton = document.querySelector('#backdrop');
  if (backdropButton) backdropButton.onclick = () => setBackdrop(!scene.background);

  return {T, renderer, scene, camera, controls, floor, key, useEnvironment, setBackdrop, rotateLights, moveCamera, onFrame, resize};
}
